# Generated by Django 4.0.4 on 2022-06-20 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordinates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('published', models.DateTimeField()),
                ('link', models.TextField(default=None, null=True)),
                ('attachment', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='attachments.attachmentmodel')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('coordinates', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinates.coordinatesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
