# Generated by Django 4.0.6 on 2023-08-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatesmodel',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=22),
        ),
        migrations.AlterField(
            model_name='coordinatesmodel',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=22),
        ),
    ]
