# Generated by Django 4.0.6 on 2023-08-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0002_alter_coordinatesmodel_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatesmodel',
            name='lat',
            field=models.DecimalField(decimal_places=20, max_digits=23),
        ),
        migrations.AlterField(
            model_name='coordinatesmodel',
            name='long',
            field=models.DecimalField(decimal_places=20, max_digits=23),
        ),
    ]
