logging.level.org.springframework.web=TRACE
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.flyway.enabled=true

# ????????? Hibernate ??? ??????????????? ????????/?????????? ??????
spring.jpa.hibernate.ddl-auto=update

# ????? SQL????????? ? ??????? (??? ???????)
spring.jpa.show-sql=true

# ?????????????? SQL????????? ??? ?????? ??????????
spring.jpa.properties.hibernate.format_sql=true

# ??????????? SQL?????????
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ??????? ?????????? ??? ????????? ?????????? ????? ? swagger
server.forward-headers-strategy=native