CREATE TABLE comment_entity
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id       BIGINT,
    author        VARCHAR(255),
    author_avatar VARCHAR(255),
    content       TEXT,
    published     BIGINT,
    CONSTRAINT pk_commententity PRIMARY KEY (id)
);

CREATE TABLE comment_entity_like_owner_ids
(
    comment_entity_id BIGINT NOT NULL,
    like_owner_ids    BIGINT
);

ALTER TABLE comment_entity
    ADD CONSTRAINT FK_COMMENTENTITY_ON_POST FOREIGN KEY (post_id) REFERENCES post_entity (id);

ALTER TABLE comment_entity_like_owner_ids
    ADD CONSTRAINT fk_commententity_likeownerids_on_comment_entity FOREIGN KEY (comment_entity_id) REFERENCES comment_entity (id);

DROP TABLE push_token_entity CASCADE;

ALTER TABLE event_entity
ALTER
COLUMN link TYPE VARCHAR(255) USING (link::VARCHAR(255));

ALTER TABLE post_entity
    ALTER COLUMN published DROP NOT NULL;

ALTER TABLE job_entity
    ALTER COLUMN start DROP NOT NULL;